import type { NextPage } from "next";
import Head from "next/head";
import Searchbar from "@components/Searchbar";

const Home: NextPage = () => {
  return (
    <div className="bg-blue-100">
      <Head>
        <title>BGK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex items-center justify-center">
        <Searchbar />
      </main>
    </div>
  );
};

export default Home;
