import type { NextPage } from "next";
import Head from "next/head";
import Searchbar from "@components/Searchbar";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="bg-blue-100">
      <Head>
        <title>BGK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex items-center justify-center">
        <div className="-mt-12">
          <div className="mb-8">
            <Image src="/logo.png" alt="logo" width={302} height={48} />
          </div>
          <Searchbar />
        </div>
      </main>
    </div>
  );
};

export default Home;
